export { default as IUser } from '@interface/model/IUser'
export { default as IDefault } from '@interface/model/IDefault'
export { ICourse, ICourseExtended } from '@interface/model/ICourse'
export { IFeedback, IFeedbackExtended } from '@interface/model/IFeedback'
export { default as IBootcamp } from '@interface/model/IBootcamp'
