enum CareerOptions {
  WebDevelopment = 'Web Development',
  MobileDevelopment = 'Mobile Development',
  UIUX = 'UI/UX',
  DataScience = 'Data Science',
  Business = 'Business',
  SoftwareEngineering = 'Software Engineering',
  FrontEndWebDevelopment = 'FRONT-END Web Development',
  BackEndWebDevelopment = 'BACK-END Web Development',
  FullStackWebDevelopment = 'FULL_STACK Web Development',
  DevOps = 'Dev Ops',
  WebDesignDevelopment = 'Web Design & Development',
  DataScienceProgram = 'Data Science Program',
  SoftwareQA = 'Software QA',
  MasteringWebDesigning = 'Mastering Web Designing',
  AndroidAppWebDevelopment = 'Android App Web Development',
  Meta = 'Meta',
  IBMDataScience = 'IBM Data Science',
  AppleiOSWebAppsDevelopment = 'Apple iOS Web Apps Development',
  BackEnd = 'Back-end',
  AI = 'AI',
  MachineLearning = 'Machine Learning',
  CloudComputing = 'Cloud Computing',
  CyberSecurity = 'Cyber Security',
  Blockchain = 'Blockchain',
  ArtificialIntelligence = 'Artificial Intelligence',
  Other = 'Other'
}

export default CareerOptions
